import math

import numpy as np
from manim import *
config.frame_width = 32
config.frame_height = 18
class Still(Scene):
    def construct(self):
        rectangle = Rectangle(height = 20.0, width = 32.0, color=BLUE_D)
        rectangle.set_fill(BLUE_D, opacity=1)
        rectangle.shift(10*DOWN)
        water_circle = Circle(radius = 2.0, color=BLUE_D)
        water_circle.set_fill(BLUE_D, opacity=1)
        water_circle.shift(11*UP)
        water_circle.set_z(5)
        water_ellipse = Ellipse(width = 4.0, height = 3.5, color=BLUE_D)
        water_ellipse.set_fill(BLUE_D, opacity=1)
        water_ellipse.set_z(5)
        water_ellipse_2 = Ellipse(width=4.0, height=3.5, color=BLUE_D)
        water_ellipse_2.shift(3.5*DOWN)
        water_ellipse_2.set_fill(BLUE_D, opacity=1)
        water_ellipse_2.set_z(5)
        air_ellipse = Ellipse(width = 5.0, height= 3.0, color=BLACK)
        air_ellipse.shift(2*UP)
        air_ellipse.set_fill(BLACK, opacity=1)
        air_ellipse.set_z(3)
        air_ellipse_2 = Ellipse(width = 5.0, height= 3.0, color=BLACK)
        air_ellipse_2.set_fill(BLACK, opacity=1)
        air_ellipse_2.set_z(3)
        air_arrow_1 = Arrow(start = [2.1, -0.5, 0], end=[2.6, 1, 0])
        air_arrow_2 = Arrow(start = [-2.1, -0.5, 0], end=[-2.6, 1, 0])
        air_text_1 = Text("air")
        air_text_2 = Text("air")
        air_text_1.shift(1.5*UP+2.6*RIGHT)
        air_text_2.shift(1.5*UP+2.6*LEFT)
        air_path = Line(start = [0, 0, 0], end = [0, 2, 0])
        water_path = Line(start = [0, 0, 0], end = [0, -2, 0])
        self.add(rectangle)
        self.add(air_ellipse)
        self.add(water_circle)
        self.play(Transform(water_circle, water_ellipse), Transform(air_ellipse, air_ellipse_2))
        self.play(FadeIn(air_arrow_1), FadeIn(air_arrow_2), FadeIn(air_text_1), FadeIn(air_text_2))
        self.wait(1)
        self.play(FadeOut(air_arrow_1), FadeOut(air_arrow_2), FadeOut(air_text_1), FadeOut(air_text_2))
        self.play(MoveAlongPath(air_ellipse, air_path), MoveAlongPath(water_circle, water_path))
        self.wait(1)
class Bounce(Scene):
    def construct(self):
        rectangle = Rectangle(height = 20.0, width = 32.0, color=BLUE_D)
        rectangle.set_fill(BLUE_D, opacity=1)
        rectangle.shift(10 * DOWN)
        water_circle = Circle(radius = 2.0, color=BLUE_D)
        water_circle.set_fill(BLUE_D, opacity=1)
        water_circle.shift(3 * UP)
        water_circle.set_z(5)
        water_circle_2 = Circle(radius=2.0, color=BLUE_D)
        water_circle_2.set_fill(BLUE_D, opacity=1)
        water_circle_2.shift(3 * UP)
        water_circle_2.set_z(5)
        water_ellipse = Ellipse(width = 4.0, height = 3.5, color=BLUE_D)
        water_ellipse.set_fill(BLUE_D, opacity=1)
        water_ellipse.set_z(5)
        water_ellipse.shift(UP)
        air_ellipse = Ellipse(width = 5.0, height= 3.0, color=BLACK)
        air_ellipse.shift(2*UP)
        air_ellipse.set_fill(BLACK, opacity=1)
        air_ellipse.set_z(3)
        air_path = Line(start=[0, 2, 0], end=[0, 0.5, 0])
        air_path_2 = Line(start = [0, 0.5, 0], end = [0, 2, 0])
        water_body_path = Line(start=[0, -10, 0], end=[0, -9.5, 0])
        water_body_path_2 = Line(start=[0, -9.5, 0], end=[0, -10, 0])
        air_arrow_1 = Arrow(start=[2.1, 0, 0], end=[2.6, 1.5, 0])
        air_arrow_2 = Arrow(start=[-2.1, 0, 0], end=[-2.6, 1.5, 0])
        air_text_1 = Text("air")
        air_text_2 = Text("air")
        air_text_1.shift(2 * UP + 2.6 * RIGHT)
        air_text_2.shift(2 * UP + 2.6 * LEFT)
        air_arrow_3 = Arrow(end=[1.1, 0.5, 0], start=[3.1, 1, 0])
        air_arrow_4 = Arrow(end=[-1.1, 0.5, 0], start=[-3.1, 1, 0])
        air_text_3 = Text("air")
        air_text_4 = Text("air")
        air_text_3.shift(1.5 * UP + 3.6 * RIGHT)
        air_text_4.shift(1.5 * UP + 3.6 * LEFT)
        force_arrow = Arrow(start=[0, 1, 0], end=[0, 4, 0])
        force_text = Text("Force by air on droplet")
        force_text.shift(4.5*UP)
        self.add(rectangle)
        self.add(air_ellipse)
        self.add(water_circle)
        self.play(Transform(water_circle, water_ellipse), MoveAlongPath(air_ellipse, air_path),
                  MoveAlongPath(rectangle, water_body_path))
        self.play(FadeIn(air_arrow_1), FadeIn(air_arrow_2), FadeIn(air_text_1), FadeIn(air_text_2), FadeIn(force_arrow),
                  FadeIn(force_text))
        self.wait(0.5)
        self.play(FadeOut(air_arrow_1), FadeOut(air_arrow_2), FadeOut(air_text_1), FadeOut(air_text_2),
                  FadeOut(force_arrow), FadeOut(force_text))
        self.play(MoveAlongPath(air_ellipse, air_path_2), Transform(water_circle, water_circle_2),
                  MoveAlongPath(rectangle, water_body_path_2))
        self.play(FadeIn(air_arrow_3), FadeIn(air_arrow_4), FadeIn(air_text_3), FadeIn(air_text_4))
        self.wait(0.5)
        self.play(FadeOut(air_arrow_3), FadeOut(air_arrow_4), FadeOut(air_text_3), FadeOut(air_text_4))
class Interaction(Scene):
    def construct(self):
        ax = Axes(
            x_range=[0, PI*8],
            y_range=[0, 18],
            x_length=32,
            y_length=18
        )
        surface = ax.plot(lambda x: np.cos(x) + 9, color=BLUE_D)
        area = ax.get_area(surface, x_range=[0, PI*8], color=(BLUE_D, BLUE_D), opacity=1)
        surface_3 = ax.plot(lambda x: np.cos(x) + 9, color=BLUE_D)
        area_3 = ax.get_area(surface, x_range=[0, PI * 8], color=(BLUE_D, BLUE_D), opacity=1)
        self.add(surface, area)
        surface_2 = ax.plot(lambda x: np.cos(x) + 9.5, color=BLUE_D)
        area_2 = ax.get_area(surface_2, x_range=[0, PI * 8], color=(BLUE_D, BLUE_D), opacity=1)
        air_ellipse = Ellipse(height=2, width=3, color=BLACK)
        air_ellipse.shift(13.5*LEFT + 2*UP)
        air_ellipse.set_fill(BLACK, opacity=1)
        water_circle = Circle(radius=1, color=BLUE_D)
        water_circle.shift(10*UP + 13.5*LEFT)
        water_circle.set_fill(BLUE_D, opacity=1)
        water_circle_2 = Circle(radius=1, color=BLUE_D)
        water_circle_2.set_fill(BLUE_D, opacity=1)
        water_circle_2.shift(12*LEFT + 1.5*UP)
        water_ellipse = Ellipse(height=1.5, width=2, color=BLUE_D)
        water_ellipse.shift(LEFT*13.5 + 0.5*UP)
        water_ellipse.set_fill(BLUE_D, opacity=1)
        air_path = Line([-13.5, 2, 0], [-13.5, 0.5, 0])
        air_path_2 = Line([-13.5, 0.5, 0], [-12, 2, 0])
        water_ellipse.rotate(-PI/6)
        air_ellipse.rotate(-PI/6)
        air_ellipse.z_index = 1
        water_ellipse.z_index = 2
        water_circle.z_index = 2
        force_arrow = Arrow(start = [-13.5, 0.5, 0], end=[-12, 2, 0])
        force_text = Text("Force by air on droplet")
        force_text.shift(11.5 * LEFT + 2.5 * UP)
        force_arrow.z_index = 3
        self.add(water_circle)
        self.play(Transform(surface, surface_2), Transform(area, area_2), MoveAlongPath(air_ellipse, air_path),
                  Transform(water_circle, water_ellipse))
        self.play(FadeIn(force_text), FadeIn(force_arrow))
        self.wait(1)
        self.play(FadeOut(force_arrow), FadeOut(force_text))
        self.play(Transform(surface, surface_3), Transform(area, area_3), MoveAlongPath(air_ellipse, air_path_2),
                  Transform(water_circle, water_circle_2))